server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    com.annihilator.hashing: INFO

sizeOfRing: 500
noOfVirtualNodes: 5
debugging: true
